### ISSUE TITLE
Pod with bandwidth test error

### ISSUE THREAD

**Issue by like-inspur** [mozhuli/kube-qos#1]
I create pod with ingress and egress bandwidth，like
kind: Pod
metadata:
  name: qos
  namespace: default
  labels:
    qos: open
  annotations:
    kubernetes.io/ingress-bandwidth: 100M
    kubernetes.io/egress-bandwidth: 100M
spec:
  containers:
  - name: test
    imagePullPolicy: IfNotPresent
    image: registry.cluster1.com:5000/iop/centos:7

But pod test bandwidth with iperf is not 100M，like
[  3] local 10.233.104.114 port 54884 connected with 10.110.20.107 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  1.09 GBytes   933 Mbits/sec

kubelet config like this，what is the reason for this
/bin/bash /usr/local/bin/kubelet --v=2 --address=10.110.20.7 --hostname-override=master1 --allow-privileged=true --pod-manifest-path=/etc/kubernetes/manifests --pod-infra-container-image=registry.cluster1.com:5000/gcr.io/google_containers/pause-amd64:3.0 --kube-reserved cpu=100m,memory=512M --node-status-update-frequency=10s --enable-cri=False --cgroup-driver=systemd --cgroups-per-qos=False --enforce-node-allocatable= --cluster-dns=10.233.0.3 --cluster-domain=cluster.local --resolv-conf=/etc/resolv.conf --kubeconfig=/etc/kubernetes/node-kubeconfig.yaml --require-kubeconfig --node-labels=node-role.kubernetes.io/master=true,manager=iop_true,node-role.kubernetes.io/node=true,worker=iop_true --network-plugin=cni --network-plugin-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin

**Comment by like-inspur** [comment]
kube-qos start like this
kube-qos -etcd-endpoint https://10.110.20.8:2379,https://10.110.20.7:2379 -kubeconfig /etc/kubernetes/node-kubeconfig.yaml -labelSelector qos=open -log_dir /var/log/kube-qos -v 2

**Comment by mozhuli** [comment]
can you paste the kube-qos log and the iperf  enviroment?

**Comment by like-inspur** [comment]
there is nothing in /var/log/kube-qos/
iperf test bandwidth in 1000M environment，server use iperf -s，client use iperf -c

**Comment by mozhuli** [comment]
kube-qos start with ./kube-qos --etcd-endpoint=http://10.96.232.136:6666 --labelSelector=qos=open --v=4   --logtostderr=true to show the log. kube-qos test with calico's alone etcd.  The use case of  k8s etcd has not tested.

**Comment by like-inspur** [comment]
I create service for etcd like this
kind: Endpoints
apiVersion: v1
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 10.110.20.7
      - ip: 10.110.20.8
    ports:
      - port: 2379


kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  ports:
  - protocol: TCP
    port: 6666
    targetPort: 2379

kue-qos start with  ./kube-qos -etcd-endpoint=https://10.233.4.211:6666 -kubeconfig=/etc/kubernetes/node-kubeconfig.yaml -labelSelector=qos=open -v=4 --logtostderr=true
log print There are 0 pods need to be limited in the cluster

**Comment by like-inspur** [comment]
pod define like this
apiVersion: v1
kind: Pod
metadata:
  name: qos
  namespace: default
  labels:
    qos: open
  annotations:
    kubernetes.io/ingress-bandwidth: 100M
    kubernetes.io/egress-bandwidth: 100M
spec:
  containers:
  - name: test
    imagePullPolicy: IfNotPresent
    image: registry.cluster1.com:5000/iop/centos:7

Is there any problem abount kube-qos with etcd connection?

**Comment by mozhuli** [comment]
As i can see, There is no problems in the service, pod yaml files. And is kube-qos running with the pod which need to be limited in the same node?

**Comment by mozhuli** [comment]
Note: kube-qos only limits the bandwidth of pods on the same node by setting tc.

**Comment by like-inspur** [comment]
The problem still exists on the same node。Is there any yaml that provide kube-qos on k8s？

**Comment by mozhuli** [comment]
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      annotations:
        kubernetes.io/ingress-bandwidth: 3M
        kubernetes.io/egress-bandwidth: 10M
      labels:
        name: nginx
        qos: open
    spec:
      containers:
      - name: nginx
      .....
```

**Comment by like-inspur** [comment]
qos limit bandwidth is the bandwidth within pod in k8s cluster，or all bandwidth in and out of pod？

**Comment by mozhuli** [comment]
only limits pods which have the annotation `kubernetes.io/ingress-bandwidth` for  ingress bandwidth and `kubernetes.io/egress-bandwidth` for egress bandwidth. And this is demo, I am plan to rework kube-qos using k8s informer framework.

**Comment by like-inspur** [comment]
Thank you，look forward to your new work
